name: golang

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: number
        default: 1.18

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: cache-${{ hashFiles('**/go.sum') }}
      - uses: andstor/file-existence-action@v1
        id: docker_compose_yml
        with:
          files: docker-compose.yml
      - run: docker-compose up -d
        if: steps.docker_compose_yml.outputs.files_exists == 'true'
      - run: go test -v ./pkg/...
      - run: docker-compose logs
        if: steps.docker_compose_yml.outputs.files_exists == 'true'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      - uses: actions/checkout@v3
      - uses: andstor/file-existence-action@v1
        id: golangci_yml
        with:
          files: .golangci.yml
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose --config .golangci.yml
        if: steps.golangci_yml.outputs.files_exists == 'true'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose
        if: steps.golangci_yml.outputs.files_exists == 'false'
